name: fitlify_flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.10.0-7.3.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^0.6.9
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  provider: ^4.3.2+2
  get_it: ^5.0.1
  injectable: ^1.0.5
  uuid: ^2.2.2
  freezed_annotation: ^0.12.0
  google_fonts: ^1.1.1
  shimmer: ^1.1.2
  kt_dart: ^0.8.0
  reorderables: ^0.3.2
  modal_bottom_sheet: 0.2.1+1-dev
  super_tooltip: ^0.9.6
  firebase_core: ^0.5.2
  firebase_auth: ^0.18.3
  firebase_crashlytics: ^0.2.3
  cloud_firestore: ^0.14.3
  dartz: ^0.9.2
  json_annotation: ^3.1.0
  pdf: ^1.11.2
  printing: ^3.7.1
  cached_network_image: ^2.3.3
  sign_in_with_apple: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  auto_route_generator: ^0.6.10
  build_runner: ^1.10.2
  mobx_codegen: ^1.1.2
  injectable_generator: ^1.0.6
  lint: ^1.3.0
  freezed: ^0.12.2
  flutter_launcher_icons: ^0.8.1
  mockito: ^4.1.3
  json_serializable: ^3.5.0
  firebase_core_platform_interface: ^2.0.0

flutter_icons:
  android: true
  ios: true
  adaptive_icon_background: "assets/app_icon/android_background.png"
  adaptive_icon_foreground: "assets/app_icon/android_foreground.png"
  image_path: "assets/app_icon/app_icon.png"

flutter:
  fonts:
    - family: FitlifyIcons
      fonts:
        - asset: assets/font/FitlifyIcons.ttf
  assets:
    - assets/font/

  uses-material-design: true
flutter_intl:
  enabled: true